[package]
name = "log4rs_gelf"
version = "0.1.0"
authors = ["Cédric Dumay <cedric.dumay@gmail.com>"]

[features]
ovh-ldp = ["serde_gelf/ovh-ldp"]

[dependencies]
log = "0.4"
log4rs = "0.8"
native-tls = "0.2"
serde = "1.0"
serde-value = "0.5"
serde_derive = "1.0"
serde_gelf = { git = "https://github.com/cdumay/rust-serde_gelf"}
serde_json = "1.0"
